### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by qinzhen123-creator** [Germey/JMeterMonitor#2]
![image](https://user-images.githubusercontent.com/61811900/79823753-0ee76e00-83c7-11ea-84ab-2155e85e748f.png)
qing'wen请问我本地怎么配置我prometheus 的路径然后生成jmx文件

**Comment by Germey** [comment]
可以参考这个 jmx 文件，https://github.com/johrstrom/jmeter-prometheus-plugin/blob/master/docs/examples/simple_prometheus_example.jmx，你用另一个 jmeter 打开，copy 过来 Prometheus Listener 就行了。

运行测试之后打开 localhost:9270，就能看到输出统计信息了，Prometheus 主动 scrape 这个收集数据，而不是主动发送到 Prometheus，所以不用配置 Prometheus 路径，是 Prometheus 配这个 JMeterMonitor 的 host。

**Comment by qinzhen123-creator** [comment]
嗯嗯 所以你的意思是我可以把你发的prometheus插件的jmx文件完全拷贝到我的服务端里面，然后把我的测试计划的jmx文件也拷贝进去  接着prometheus那边直接配置抓取jmeter的路径就可以了是吧  还有两个问题麻烦请教一下： 我是运维人员 第一次用jmeter 看网上都是直接测试一次生成报告 linux端如何使这个jmeter保持运行？第二个问题 prometheus的jmx 和我testplan的jmx 要必须放到一个文件里面吗 还是可以分开

**Comment by Germey** [comment]
不用，就是它的 jmx 文件里面不是有个 Prometheus Listener 配置吗？就只把这个拷贝到你的 test plan 就行了，就只用你自己的 jmx 文件就行了，我发你的这个仅仅让你拷贝 Prometheus Listener 配置用的，因为对比着敲不是很麻烦嘛。

jmx 除了 ui 模式还有命令行模式的，我已经打包到 docker 里面了，可以直接用。

**Comment by qinzhen123-creator** [comment]
嗯嗯  这个我已经解决了 现在prometheus 和grafana都能得到数据了  但是问题是这web service 暴露出来的这些数据有点看不懂  可以直接给我一个你的grafana模板吗  我想参考一下

**Comment by Germey** [comment]
可以看下这个 https://github.com/johrstrom/jmeter-prometheus-plugin/blob/master/docs/examples/grafana_jsr223_test.json

**Comment by qinzhen123-creator** [comment]
好的 感谢
